/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Cliente;
import Clases.Credito;
import Clases.Cuenta;
import Clases.Debito;
import Clases.Funciones;
import Clases.TarjetaDeCredito;
import Recursos.BaseDeDatos;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Grupo 4
 */
public class ConsultaSaldo extends javax.swing.JDialog {

    /**
     * Creates new form ConsultaSaldo
     */
    Cliente User;
    Debito[] Debitos;
    BaseDeDatos Con;
    JFrame Menu;

    public ConsultaSaldo(Cliente User, JFrame menu, BaseDeDatos con, Debito[] debitos) {
        /*
            Configuramos la ventana  
         */
        this.setResizable(false);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.pack();
        this.setModal(true);

        this.User = User;
        this.Menu = menu;
        this.Debitos = debitos;
        this.Con = con;
        initComponents();

        CargarDatosDeCuenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NroC = new javax.swing.JLabel();
        TIDC = new javax.swing.JLabel();
        SaldoC = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DebitoLabel = new javax.swing.JLabel();
        CreditoLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cancelar = new rojerusan.RSButtonMetro();
        rSButtonMetro1 = new rojerusan.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estado de cuenta");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 560, 90));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nro de Cuenta:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Titular de la cuenta:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Saldo Disponible:");

        NroC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NroC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        NroC.setText("123");
        NroC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TIDC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TIDC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TIDC.setText("Armando Cecilio Casas Urbaneta");
        TIDC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SaldoC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SaldoC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SaldoC.setText("2.745.500");
        SaldoC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Debito:");

        DebitoLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DebitoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DebitoLabel.setText("400.000");
        DebitoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        CreditoLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CreditoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CreditoLabel.setText("20.000");
        CreditoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Credito:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(DebitoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SaldoC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NroC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TIDC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addComponent(CreditoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NroC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TIDC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaldoC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DebitoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreditoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 610, 310));

        cancelar.setBackground(new java.awt.Color(102, 102, 102));
        cancelar.setForeground(new java.awt.Color(0, 0, 0));
        cancelar.setText("Volver");
        cancelar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 170, 60));

        rSButtonMetro1.setText("Imprimir");
        rSButtonMetro1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 190, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        Funciones.MensajeDeAlerta(3, "Atencion", String.format("%s%s%s", "Impresion de ", "ticket", ""));
        Funciones.generarPdf(new String[]{"\tResumen de cuenta",
            "Numero de Cuenta: ", NroC.getText() ,
            "Nombre:", TIDC.getText(),
            "Saldo Total:", this.SaldoC.getText(),
            "Targeta de Credito:" , this.CreditoLabel.getText(),
            "Targeta de Debito:" , this.DebitoLabel.getText()
        });
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Funciones.deseaSalir(this, Menu);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     * @param Usuario
     * @param VentanaAnterior
     * @param Con
     * @param debitos
     */
    public static void main(String args[], Cliente Usuario, JFrame VentanaAnterior, BaseDeDatos Con, Debito[] debitos) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaSaldo(Usuario, VentanaAnterior, Con, debitos).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CreditoLabel;
    private javax.swing.JLabel DebitoLabel;
    private javax.swing.JLabel NroC;
    private javax.swing.JLabel SaldoC;
    private javax.swing.JLabel TIDC;
    private rojerusan.RSButtonMetro cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSButtonMetro rSButtonMetro1;
    // End of variables declaration//GEN-END:variables

    // se debe efectivisar la transferencia de dinero
    private void EfectivisarTransferencia(String cuenta, int monto, String pinTr) throws Exception {
        /*
            Aqui deberia ir la inserccion en la base de datos
         */
        if (monto > 25000000) {
            throw new UnsupportedOperationException("Saldo insuficiente");
        }

        JOptionPane.showMessageDialog(null, "Transferencia de dinero completa", "Operacion Exitosa", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }

    private void CargarDatosDeCuenta() {
        // cuenta
        NroC.setText(Con.getCuentas(User)[0].getID() + "");
        // titular
        TIDC.setText(User.getNombre());
        
        // debito
        int Debito = (Con.getCuentasDebitos(Con.getCuentas(User))[0].getMonto());
        
        DebitoLabel.setText(Funciones.setMoneyFormat(Debito + "") + " gs.");
        // credito
        Credito[] Credits = Con.getCuentasCreditos(Con.getCuentas(User));
        TarjetaDeCredito[] targetas = Con.getTargetaCreditos(Credits);
        int ultimoCredito = 0;
        for (int i = 0; i < targetas.length; i++) {
            ultimoCredito = targetas[i].getMonto();
        }
        CreditoLabel.setText(Funciones.setMoneyFormat(ultimoCredito + "") + " gs.");
        
        // total disponible en cuenta
        int Monto = (Debito + ultimoCredito);
        SaldoC.setText(Funciones.setMoneyFormat(Monto + "") + " gs.");
        
    }

}
